### ISSUE TITLE
Adding Binary Search Algorithm

### ISSUE THREAD

**Issue by Shashwat545** [Synergise-IIT-Bhubaneswar/Beta-Algo#1]
## Proposal

Add binary search algorithm.

## Describe the solution you'd like
Binary search is an efficient approach to search a particular element from a sorted array of numbers.

How does it work?

You have a sorted array consisting of X elements, and you input the value to be found in it. The algorithm compares your input value with the key value of the array's middle element. So here we have 3 scenarios

- If input key value matches the key value of the middle element, then its index is returned.
- If input key value is lesser than the key value of middle element, then we do a search on the sub array to the left of the middle element.
- Similarly if the input key value is greater than key value of middle element, then we do a search on the sub array to the right of the middle element.

<h3> Have you read the <a href ="https://github.com/Rj-coder-iitian/Beta-Algo/blob/main/CONTRIBUTING.md">Contributing Guidelines on Pull Requests? </a></h3>
Yes

## Please answer the following questions for yourself before submitting an issue.
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by ag278** [comment]
@Shashwat545 the title and description must contain about the algorithm, not its language. You can mention in the comment section the language that you want to take. Change the issue accordingly and add the language in which  you want to get assigned in the comments

**Comment by ag278** [comment]
Assigned Binary search in C++ to @Shashwat545  .
